version: '3'
services:
  database:
    container_name: dlpiper-database
    restart: always
    image: "postgres:11"
    env_file:
      - database.env
    volumes:
      - dlpiper-data:/var/lib/postgresql/data/
volumes:
  dlpiper-data:
